-- 회원 전체
SELECT * FROM HANA_MEMBER;


-- 계좌 전체
SELECT A.ACCOUNT_NUMBER "계좌번호",
B.NAME "은행명",
A.ACCOUNT_PW "계좌비밀번호",
A.BALANCE "계좌잔액",
A.ALIAS "계좌 별칭",
M.NAME "계좌주",
A.OFTEN_USED "통합계좌 등록여부",
A.OPENING_DATE,
P.NAME,
B.NAME,
A.MEMBER_ID,
M.RESIDENT_NUMBER
FROM HANA_ACCOUNT A, HANA_MEMBER M, BANK B, HANA_PRODUCT P
WHERE A.MEMBER_ID = M.ID AND A.BANK_CODE = B.CODE AND A.TYPE = P.CODE;

select * FROM HANA_ACCOUNT A, HANA_MEMBER M, BANK B, HANA_PRODUCT P
WHERE A.MEMBER_ID = M.ID AND A.BANK_CODE = B.CODE AND A.TYPE = P.CODE;

-- 거래 로그 전체 
SELECT 
SEQ "시퀀스", 
L.LOG_DATE "거래일자", 
(SELECT NAME FROM BANK WHERE CODE = L.OWNER_CODE) "보내는 사람 은행", 
L.OWNER_ACCOUNT "보내는 사람 계좌",  
(SELECT NAME FROM BANK WHERE CODE = L.TARGET_CODE) "받는 사람 은행",
L.TARGET_ACCOUNT  "받는 사람 계좌 ", L.AMOUNT, T.NAME
FROM HANA_BANKING_LOG L, BANKING_TYPE T
WHERE L.TYPE_CODE = T.CODE;





UPDATE HANA_ACCOUNT SET ALIAS = ''
WHERE ACCOUNT_NUMBER = ''
AND BANK_CODE = (SELECT * FROM BANK WHERE NAME = '')
AND MEMBER_ID = '';



DELETE FROM HANA_ACCOUNT 
WHERE ACCOUNT_NUMBER = ''
AND BANK_CODE = (SELECT * FROM BANK WHERE NAME = '')
AND MEMBER_ID = '';



UPDATE HANA_ACCOUNT SET OFTEN_USED = 'Y'
WHERE BANK_CODE = (SELECT CODE FROM BANK WHERE NAME = '신한')
AND ACCOUNT_NUMBER = '113-000000082-001'
AND MEMBER_ID = 'spring';

ROLLBACK;

SELECT * FROM HANA_ACCOUNT 
WHERE BANK_CODE = (SELECT CODE FROM BANK WHERE NAME = '신한')
AND ACCOUNT_NUMBER = '113-000000082-001'
AND MEMBER_ID = 'spring';


SELECT COUNT(*) FROM HANA_ACCOUNT A, BANK B WHERE B.CODE = A.BANK_CODE
AND A.ACCOUNT_NUMBER = '113-000000082-001'
AND B.NAME =  '신한'
AND A.ACCOUNT_PW = '1993';