/*
CREATE TABLE TST_CUSTOMER2(
    ID VARCHAR2(8) NOT NULL,
    PWD VARCHAR2(8) CONSTRAINT TST_CUSTOMER2_PWD_NN NOT NULL,
    NAME VARCHAR2(20), 
    SEX CHAR(1) CONSTRAINT TST_CUSTOMER2_SEX_CK CHECK(SEX IN ('M', 'F')), 
    AGE NUMBER(3) CHECK (AGE > 0 AND AGE < 100)
);
*/

-- 한국 내 은행 코드
CREATE TABLE BANK (
    CODE NUMBER(3) CONSTRAINT BANK_CODE_PK PRIMARY KEY, -- 은행코드
    NAME VARCHAR2(30) NOT NULL CONSTRAINT BANK_NAME_UK UNIQUE -- 은행명
);


-- 한국 국민 계좌 개설 내역

CREATE TABLE OPENING_HISTORY (
    RESIDENT_NUMBER VARCHAR2(14) CONSTRAINT OPEN_ACCOUNT_NUM_PK PRIMARY KEY, -- 주민번호
    ACCOUNT_NUMBER VARCHAR2(30) NOT NULL, -- 계좌번호
    BANK_CODE NUMBER(3)NOT NULL,
    OPENING_DATE DATE NOT NULL,
    CONSTRAINT OPENING_BANK_FK FOREIGN KEY(BANK_CODE)
         REFERENCES BANK(CODE)
);


-- 하나은행 멤버
CREATE TABLE HANA_MEMBER(
    ID VARCHAR2(14)CONSTRAINT HANA_MEM_ID_PK PRIMARY KEY,
    PW VARCHAR2(30) NOT NULL,
    RESIDENT_NUMBER VARCHAR2(14) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    AGE NUMBER(4) NOT NULL CONSTRAINT HANA_MEM_AGE_CK CHECK(AGE > 0 AND AGE < 1000),
    SEX CHAR(1) DEFAULT 'M' CONSTRAINT HANA_MEM_SEX_CK CHECK(SEX IN('M', 'F')),
    JOIN_DATE DATE DEFAULT SYSDATE
);

-- 하나은행 계좌
CREATE TABLE HANA_ACCOUNT(
    ACCOUNT_NUMBER VARCHAR2(30) CONSTRAINT HANA_ACNT_NUM_PK PRIMARY KEY,
    MEMBER_ID VARCHAR2(14) NOT NULL,
    ACCOUNT_PW NUMBER(4) NOT NULL, -- 음수 나오면 안됨, 무조건 4자리 숫자
    BALANCE NUMBER(38) NOT NULL,
    ALIAS VARCHAR2(30),
    OFTEN_USED CHAR(1) DEFAULT 'N' CONSTRAINT HANA_ACNT_OFTEN_CK CHECK(OFTEN_USED IN('Y', 'N')),
    LIMIT_AMOUNT NUMBER(20) CONSTRAINT HANA_ACNT_LIMIT_CK CHECK (LIMIT_AMOUNT > 0),
    OPENING_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT HANA_ACNT_ID_FK FOREIGN KEY(MEMBER_ID) REFERENCES HANA_MEMBER(ID)
);

-- 오픈 뱅킹 신청
CREATE TABLE HANA_OPEN_BANKING_MEMBER(
    OPEN_MEM_SEQ NUMBER(30) CONSTRAINT OPEN_MEM_SEQ_PK PRIMARY KEY,
    MEMBER_ID VARCHAR2(14) NOT NULL,
    OPEN_PW NUMBER(4) NOT NULL, -- 음수 나오면 안됨, 무조건 4자리 숫자
    CONSTRAINT OPEN_MEM_ID_FK FOREIGN KEY(MEMBER_ID) REFERENCES HANA_MEMBER(ID)
);


-- 오픈 뱅킹 계좌 리스트
CREATE TABLE HANA_OPEN_BANKING_ACCOUNT (
    OPEN_ACNT_SEQ NUMBER(30) CONSTRAINT OPEN_ACNT_SEQ_PK PRIMARY KEY,
    OPEN_MEM_SEQ NUMBER(30) NOT NULL,
    BANK_CODE NUMBER(3) NOT NULL, -- 뱅크코드는 무조건 3자리 숫자 000 부터 시작
    ACCOUNT_NUMBER VARCHAR2(30) NOT NULL,
    REGDATE DATE DEFAULT SYSDATE,
    CONSTRAINT OPEN_ACNT_BANK_FK FOREIGN KEY(BANK_CODE) REFERENCES BANK(CODE),
    CONSTRAINT OPEN_ACNT_MEM_FK FOREIGN KEY(OPEN_MEM_SEQ) REFERENCES HANA_OPEN_BANKING_MEMBER(OPEN_MEM_SEQ)
);



-- 다 하고 시퀀스 만들기

-- 은행 코드 시퀀스 : 0부터 시작해서 000/001/002
CREATE SEQUENCE BANK_CODE_SEQ
    INCREMENT BY 1
    START WITH 0
    MAXVALUE 999999999999
    MINVALUE 0
    NOCYCLE;

-- 오픈뱅킹 멤버 시퀀스 : 1부터 시작 1/2/3/4
CREATE SEQUENCE OPEN_BANKING_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 999999999999
    MINVALUE 1
    NOCYCLE;
    
    
-- 오픈뱅킹 시퀀스 : 1부터 시작 1/2/3/4
CREATE SEQUENCE OPEN_BANKING_ACCOUNT_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 999999999999
    MINVALUE 1
    NOCYCLE;
    
